### ISSUE TITLE
Double defined leader mapping for ,a=

### ISSUE THREAD

**Issue by martinemde** [lanej/dotfiles#9]
I'm wondering how you fixed this. It seems to come down like this:

```
Error detected while processing dotfiles/vim/plugin/AlignMapsPlugin.vim:
line   71:
E227: mapping already exists for ,a=
```

I was thinking maybe I just have a ton of crap in my dotfiles, but it happened to a co-worker who installed your dotfiles to setup vim from scratch.

**Comment by lanej** [comment]
@martinemde i believe you have to run `AlignMapsClean` or something like that just once.

**Comment by lanej** [comment]
i could also be wrong and it is actually specified twice.

**Comment by martinemde** [comment]
I'm having trouble even getting rid of the error. Obviously <leader>a= is nice to have, but AlignMaps is overriding it. Even `noremap` doesn't work.

I'll update if I figure it out. Hope you're doing well.
